### ISSUE TITLE
Elements to look at

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-admin#2]
Here's a list of elements you probably want to use in lancie-admin:

- https://elements.polymer-project.org/elements/google-chart
- https://elements.polymer-project.org/elements/google-analytics
- https://vaadin.com/elements/-/element/vaadin-grid

**Comment by MatthijsKok** [comment]
Currently looking at [paper-datatable](https://beta.webcomponents.org/element/David-Mulder/paper-datatable)

**Comment by TimvdLippe** [comment]
That element has not been maintained for over a year, I would advise not to
use it.

Op wo 18 jan. 2017 om 14:46 schreef Matthijs Kok <notifications@github.com>:
