### ISSUE TITLE
Show date of birth when registering

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-admin#24]
The date of birth should be shown when registering to check if the filled in value matches with the date on the ID.

**Comment by dsluijk** [comment]
Not relevant for 2020, but could be useful for 2021

**Comment by bramvankooten** [comment]
This is already implemented last year. I see we made a new issue for it #90 

This is implemented in pr #92

**Comment by dsluijk** [comment]
Right, that's a bit less work then. Thank you for the notice!
