### ISSUE TITLE
Unexpected token '<' in Safari

### ISSUE THREAD

**Issue by svenpopping** [AreaFiftyLAN/lancie-admin#38]
Due to an the syntax error Unexpected token '<' the admin panel will not load in Safari

**Comment by skamoen** [comment]
Same issue in Firefox, so it's an issue with the polyfills most likely. It does work locally in firefox though...

**Comment by skamoen** [comment]
`yarn build` only puts the webcomponentsjs loader in the `build` folder, where it actually should be loading all javascript files
